---
engines:
  duplication:
    enabled: true
    config:
      languages:
        ruby:
        javascript:
        python:
        php:
          mass_threshold: 20
  phan:
      enabled: true
      config:
        file_extensions: "php"
        ignore_undeclared: true
        dead_code_detection: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
  phpcodesniffer:
    enabled : true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- tests/
- .atoum.php
