---
engines:
  duplication:
    enabled: true
    config:
      languages:
        ruby:
        javascript:
        python:
        php:
          mass_threshold: 20
  phan:
      enabled: true
      config:
        file_extensions: "php"
<<<<<<< HEAD
=======
        ignore-undeclared: true
        dead-code-detection: true
>>>>>>> 8a7a6eb0a9d46bdd0c94c409f66e20333c70a1bf
  fixme:
    enabled: true
  phpmd:
    enabled: true
  phpcodesniffer:
    enabled : true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- tests/
<<<<<<< HEAD
=======
- .atoum.php
>>>>>>> 8a7a6eb0a9d46bdd0c94c409f66e20333c70a1bf
