addons:
    code_climate:
        repo_token: 2f8245884c4ae619bc9c61aeaacbd101e31c2586b6646a110a02d51f079df6db
language: php
php:
  - '7.0'
before_script:
  - mkdir -p build/logs/
script: 
  - composer install --no-interaction --dev
  - ./vendor/bin/atoum -d tests/units -c .atoum.php
  - CODECLIMATE_REPO_TOKEN=2f8245884c4ae619bc9c61aeaacbd101e31c2586b6646a110a02d51f079df6db ./vendor/bin/test-reporter
notifications:
  on_success: change
  on_failure: change
